function stochastic_vars = frbus_stochastic_vars_backward()
%FRBUS_STOCHASTIC_VARS_BACKWARD 64 FRB/US stochastic variables used in demo.
stochastic_vars = { ...
    'ebfi','ecd','ech','eco','egfe','egfen','egfet','egfl','egse', ...
    'egsen','egset','egsl','eh','emo','emp','ex','fpxrr','fxgap', ...
    'ugfsrp','gtn','gtr','gtrd','hmfpt','hqlfpr','hqlww','ki','leg', ...
    'leo','lfpr','lhp','lurnat','lww','mfpt','pbfir','pcer', ...
    'pcfr','pegfr','pegsr','phouse','phr','picxfe','pieci','pmo', ...
    'poilr','pxr','rbbbp','rcar','rcgain','reqp','rfynic', ...
    'rfynil','rg10p','rg30p','rg5p','rgfint','rme','tcin','tpn', ...
    'trci','trp','trpt','uynicpnr','ynidn','ynirn' ...
    };
end
